/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    ACol: typeof import('ant-design-vue/es')['Col']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARate: typeof import('ant-design-vue/es')['Rate']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    copy: typeof import('./src/components/xiFrom/index copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    'Index copy': typeof import('./src/components/xiFrom/index copy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuperFrom: typeof import('./src/components/superFrom/index.vue')['default']
    SuperInput: typeof import('./src/components/superFrom/components/superInput.vue')['default']
    SuperRadio: typeof import('./src/components/superFrom/components/superRadio.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
    XCheckbox: typeof import('./src/components/superFrom/components/xCheckbox.vue')['default']
    XiAudio: typeof import('./src/components/xiFrom/components/XiAudio.vue')['default']
    XiCheckbox: typeof import('./src/components/xiFrom/components/XiCheckbox.vue')['default']
    XiFrom: typeof import('./src/components/xiFrom/index.vue')['default']
    XiInput: typeof import('./src/components/xiFrom/components/XiInput.vue')['default']
    XiInputNumber: typeof import('./src/components/xiFrom/components/XiInputNumber.vue')['default']
    XInput: typeof import('./src/components/superFrom/components/xInput.vue')['default']
    XiRadio: typeof import('./src/components/xiFrom/components/XiRadio.vue')['default']
    XiSelect: typeof import('./src/components/xiFrom/components/XiSelect.vue')['default']
    Xislider: typeof import('./src/components/superFrom/components/Xislider.vue')['default']
    XiSlider: typeof import('./src/components/xiFrom/components/XiSlider.vue')['default']
    XiSwitch: typeof import('./src/components/xiFrom/components/XiSwitch.vue')['default']
    XiTextarea: typeof import('./src/components/xiFrom/components/XiTextarea.vue')['default']
    XRadio: typeof import('./src/components/superFrom/components/xRadio.vue')['default']
  }
}
